CREATE TABLE User_ (
    UserID BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL,
    UserEmail VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    RoleID INT NOT NULL DEFAULT(2),
    FOREIGN KEY (RoleID) REFERENCES UserRoles(RoleID)
)