### GET ALL NOTES
GET http://localhost:3000/notes

### GET ONE NOTE
GET http://localhost:3000/notes/23NVU8UTV4BIFT9034

### POST A NOTE
POST http://localhost:3000/notes
Content-Type: application/json

{
    "NoteID": "Mobile app development",
    "NoteTitle": "Develop a mobile app for the business",
    "NoteContent": "2022-05-31"
}

### UPDATE A PROJECT
PUT http://localhost:3000/notes/6
Content-Type: application/json

{
    "NoteID": "Mobile app development",
    "NoteTitle": "Develop a mobile app for the business",
    "NoteContent": "2022-05-31"
}

### DELETE A PROJECT
DELETE  http://localhost:3000/notes/23NVU8UTV4BIFT9034