### GET ALL NOTES
GET http://localhost:3000/notes

### GET ONE NOTE
GET http://localhost:3000/notes/23NVU8UTV4BIFT9034

### POST A NOTE
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Mobile app development",
    "content": "Develop a mobile app for the business",
    "created_at":""
}

### UPDATE A PROJECT
PUT http://localhost:3000/notes/1a6f0efe-9531-4d9f-b923-32c92eca38d6
Content-Type: application/json

{
    "title": "Web app development",
    "content": "Develop a web app for the business",
    "created_at":"2024-06-05"
}

### DELETE A PROJECT
DELETE  http://localhost:3000/notes/23NVU8UTV4BIFT9034